{% set name = "xtiff" %}
{% set version = "0.7.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xtiff-{{ version }}.tar.gz
  sha256: a77a30686fded43645b748be9a8cef9a6316b079e59b3163f7b52e2e294881d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - numpy
    - python >={{ python_min }}
    - tifffile >=2022.4.22

test:
  imports:
    - xtiff
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/BodenmillerGroup/xtiff
  summary: A tiny Python library for writing multi-channel TIFF stacks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jwindhager
